name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: "Run ruff via nox"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"
          python-version: "3.13"

      - name: Run ruff via nox
        run: |
          uv run nox -s format_check

  pyright:
    runs-on: ubuntu-latest
    name: "Run pyright via nox"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"
          python-version: "3.13"

      - name: Run pyright via nox
        run: |
          uv run nox -s pyright
  sqlc:
      runs-on: ubuntu-latest
      name: "Run sqlc verify via nox"
      steps:
          # Ensure sqlc is installed
          - name: Install sqlc
            uses: sqlc-dev/setup-sqlc@v4
            with:
              sqlc-version: '1.25.0'
          # Print out the current version
          - run: |
             sqlc version
          - name: Install uv
            uses: astral-sh/setup-uv@v5
            with:
              version: "0.6.9"
              python-version: "3.13"
          - name: Run sqlc verify via nox
            run: |
                  uv run nox -s sqlc_verify



