name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: "Run ruff via nox"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"
          python-version: "3.13"

      - name: Run ruff via nox
        run: |
          uv run nox -s format

  pyright:
    runs-on: ubuntu-latest
    name: "Run pyright via nox"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"
          python-version: "3.13"

      - name: Run pyright via nox
        run: |
          uv run nox -s pyright
